### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by michael-grunder** [dw/csvmonkey#1]
Hi,

Thanks for writing such an awesome library and putting it up on GitHub.  As far as I can tell this is the fastest CSV parser on the planet.

I'm thinking about creating a C wrapper to the library but there is no licensing information here.  Would you be open to adding a license?

Cheers!
Mike

**Comment by dw** [comment]
HTH HAND :)

**Comment by dw** [comment]
If you want to structure your C wrapper as a pull request, that would be awesome. Probably it'd be nice if you had at least one StreamCursor implementation that took its input from a function pointer, and perhaps a variant of that which avoided buffering too somehow.

Some of the speed is due to template specialization, so it might be nice to put this straight in the C++ header file (or just define it for yourself in your own code, whatever suits)

**Comment by michael-grunder** [comment]
I'll gladly contribute the wrapper back as a pull request once I get something working.  I'm sure there are many pure C projects that would like an alternative to libcsv.

A generic function pointer based cursor also sounds like a good plan.

Thanks!
Mike

**Comment by michael-grunder** [comment]
Hi,

It's a work in progress, but I've got the parser working as a shared object.  I made a couple of small changes to the parser itself to take care of some valgrind complaints but tried to maintain a light touch.

I'll open a PR once I do some more testing and figure out something sane to do around error handling.  😃

https://github.com/michael-grunder/csvmonkey

**Comment by dw** [comment]
Very cool! Will inspect shortly. Do you have any kind of benchmark before/after with all the extra indirections introduced? It should not amount to more than one per row, but still curious if it hurts
