### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by Yomguithereal** [dw/csvmonkey#3]
As requested I open this issue @dw. Would be nice to have a python3 version.

**Comment by dw** [comment]
This partially works now, but it has revealed a glaring bug with the Python extension. Memory is allocated by Python aligned to 8 bytes, not 16, so it is possible to cause a segmentation fault due to random chance of how the allocator's alignment turned out.

Fixing this is a pain, because the reader object supports GC, and GC objects /must/ use the Python-provided functions. So either it is hacked to avoid them, or an extra memory indirection is introduced pretty much everywhere

**Comment by Yomguithereal** [comment]
I am sorry to hear that. This seems like a nasty bug to fix. Tell me if I can be of any help.

**Comment by dw** [comment]
Fixed on master
